version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vlin*560
      MYSQL_DATABASE: spring_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Vlin*560
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
